spring:
  data:
    mongodb:
      host: 3.36.100.10
      port: 17017
      username: admin
      password: admin
      database: Portfolio
      authentication-database: admin
  messages:
    basename: i18n/exception
    encoding: UTF-8
  profiles:
    active: local
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: 9111