spring:
  data:
    mongodb:
      host: 15.164.100.178
      port: 27017
      username: admin
      password: asdzxc852!
      database: Portfolio
      authentication-database: admin
  messages:
    basename: i18n/exception
    encoding: UTF-8
  profiles:
    active: local
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: 9111