spring:
  data:
    mongodb:
      host: 192.168.10.41
      port: 27017
      username: 3view
      password: 3view
      database: Test
      authentication-database: admin
  messages:
    basename: i18n/exception
    encoding: UTF-8
  profiles:
    active: local
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: 9111